### ISSUE TITLE
Make RandomizedTesting into a separate library

### ISSUE THREAD

**Issue by clambertus** [apache/lucenenet#257]
We have ported the generators from <a href="https://github.com/randomizedtesting/randomizedtesting" class="external-link" rel="nofollow">RandomizedTesting</a> that Lucene.NET needs to support its tests and added this code to the TestFramework (unlike Lucene), both as [a static utility class](https://github.com/apache/lucenenet/blob/2731bfd4443cb12af664c03d0683b938884f1448/src/Lucene.Net.TestFramework/Util/TestUtil.cs#L240-L720) and as [extension methods](https://github.com/apache/lucenenet/blob/2731bfd4443cb12af664c03d0683b938884f1448/src/Lucene.Net.TestFramework/Support/RandomExtensions.cs). The generators we have now in the TestFramework are probably enough to cover most random testing use cases for end users.

That said, it would be useful for the .NET community at large if the random generators were made into a separate library so randomized test data can be easily generated without referencing the Lucene.NET test framework. The latest version of RandomizedTesting has more options for generating random data than what we have ported.

The library should be named after <a href="https://github.com/randomizedtesting/randomizedtesting/tree/master/randomized-runner/src/main/java/com/carrotsearch/randomizedtesting/generators" class="external-link" rel="nofollow">RandomizedTesting</a> (possibly RandomizedTesting.Generators) so that someday if the test runner is also ported (see #264), there is a logical way to integrate it.

This task would make a great little project for anyone who wants to contribute to the Lucene.NET effort.

<i>JIRA link - <a href="https://issues.apache.org/jira/browse/LUCENENET-635">[LUCENENET-635]</a> created by nightowl888</i>

**Comment by NightOwl888** [comment]
I'm changing the priority of this because there are at least 3 different places where centralizing random generators would be useful:

- [Lucene.Net.TestFramework](https://github.com/apache/lucenenet/tree/2731bfd4443cb12af664c03d0683b938884f1448/src/Lucene.Net.TestFramework/Support/Randomized/Generators)
- [Morfologik.TestFramework](https://github.com/NightOwl888/Morfologik.Stemming/tree/c8c5492c391a736277015bc0fc6567eab347638b/src/Morfologik.TestFramework/RandomizedTesting/Generators)
- Planned Benchmark Projects (See #310 and https://github.com/apache/lucenenet/pull/349#issuecomment-698747477)

Given the fact that these generators have evolved over time and don't likely have any breaking backward changes, porting the latest released version of the [generators](https://github.com/randomizedtesting/randomizedtesting/tree/release/2.7.8/randomized-runner/src/main/java/com/carrotsearch/randomizedtesting/generators) and their [associated tests](https://github.com/randomizedtesting/randomizedtesting/tree/release/2.7.8/randomized-runner/src/test/java/com/carrotsearch/randomizedtesting/generators) would probably be the right approach. Most likely any differences in behavior are bug fixes and important design changes that would be better to have than to not have.

In the case of benchmarks, using random generators is useful because it allows us to create repeatable benchmarks with large amounts of data without having to store the data in our repo.
