### ISSUE TITLE
Setup tests on additional platforms that .NET Standard supports

### ISSUE THREAD

**Issue by clambertus** [apache/lucenenet#258]
<p>We have recently setup an Azure DevOps YAML build configuration, which makes adding testing environments easier to our CI process. Adding tests to ensure support on macOS and Linux has been completed already, and (fortunately) the number of bugs that were found was fairly minimal (most of them were addressed in beta00006). However, there are other platforms .NET Standard supports that are commonly in use by Lucene.NET users which we should also setup our tests to run on.</p>

<p>Looking through the JIRA and GitHub issues, 4 platforms that have been mentioned are:</p>

* ~~Mono~~
* ~~UWP~~ - [UWP is now deprecated](https://visualstudiomagazine.com/articles/2021/10/19/uwp-migration.aspx)
* ~~Xamarin iOS~~
* [ ] [.NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/what-is-maui)
* [x] .NET Framework x86
* [x] .NET 6

<p>We should do a survey to find out what other platforms may be commonly in use and make the determination how important it is to test on them, and of course take into consideration whether the tests require a special setup that Azure Pipelines doesn't provide on any of the <a href="https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops" class="external-link" rel="nofollow">Microsoft-hosted agents</a>.</p>
<i>JIRA link - <a href="https://issues.apache.org/jira/browse/LUCENENET-633">[LUCENENET-633]</a> created by nightowl888</i>

**Comment by NightOwl888** [comment]
MAUI will be a [release candidate in April, 2022](https://github.com/dotnet/maui/wiki/roadmap#net-maui-release-candidate-april-2022).

There are a set of xUnit tests noted here: https://github.com/dotnet/maui/issues/2112#issuecomment-1073307339. Looks like no specialized runner is required like was the case on Xamarin, so NUnit should work (in theory).

**Comment by paulirwin** [comment]
Split apart testing on iOS and Android as #1031, given that is specific to those OSes and not MAUI itself. Closing this issue as otherwise effectively completed.

As far as target frameworks go, MAUI can use OS-specific TFMs like `net8.0-ios`, but this is a superset of the functionality in its base TFM (`net8.0` for `net8.0-ios`). And given that Lucene.NET does not target any OS-specific TFMs, we should have no API compatibility issues there. More info: https://learn.microsoft.com/en-us/dotnet/standard/frameworks#net-5-os-specific-tfms

We also do not use any MAUI APIs, so that is not a concern with tests.

If it is feasible for us to use xharness to run tests on iOS and Android, and someone has the bandwidth to help contribute support for that, we can evaluate that for 4.8, but until then I think we can consider the Lucene.NET API surface that would run under MAUI generally tested for Windows, Linux, and macOS via our existing tests with the base TFMs.
