### ISSUE TITLE
Fix asserts that are failing on .NET Standard 2.0

### ISSUE THREAD

**Issue by clambertus** [apache/lucenenet#267]
<p>There are a few asserts that fail on .NET Standard 2.0. They have been conditionally compiled out of the code due to the fact that on .NET Core 2.1 they cause the test runner to fatally crash, however these are a sign that something could be seriously wrong with the codecs (possibly causing index corruption).</p>

<p>Here are the known failures:</p>
<ul>
	<li><a href="https://github.com/apache/lucenenet/blob/ecf62129099d04a95edce3fca1243c7b4d2fac6b/src/Lucene.Net/Codecs/Lucene3x/Lucene3xTermVectorsReader.cs#L822-L828" class="external-link" rel="nofollow">Lucene3xTermVectorsReader</a></li>
	<li><a href="https://github.com/apache/lucenenet/blob/ecf62129099d04a95edce3fca1243c7b4d2fac6b/src/Lucene.Net/Codecs/Lucene40/Lucene40TermVectorsReader.cs#L811-L815" class="external-link" rel="nofollow">Lucene40TermVectorsReader</a></li>
	<li><a href="https://github.com/apache/lucenenet/blob/ecf62129099d04a95edce3fca1243c7b4d2fac6b/src/Lucene.Net/Codecs/BlockTreeTermsWriter.cs#L437-L439" class="external-link" rel="nofollow">BlockTreeTermsWriter</a></li>
</ul>

<i>JIRA link - <a href="https://issues.apache.org/jira/browse/LUCENENET-624">[LUCENENET-624]</a> created by nightowl888</i>

**Comment by NightOwl888** [comment]
It turns out this is a design feature of Lucene that is used for testing. The asserts were failing by design in order to be "caught" in the [BaseTermVectorsFormatTestCase](https://github.com/apache/lucenenet/blob/cffc8ddd668841eaf82cf759f976ba90aa233002/src/Lucene.Net.TestFramework/Index/BaseTermVectorsFormatTestCase.cs#L637-L647). This becomes an issue on .NET Standard, because it is set up to cause a fatal crash when an assertion is thrown.

I am still analyzing what the options are, but I suspect that consistently throwing an `InvalidOperationException` in each of the `DocsAndPostionsEnum` subclasses will likely be the answer.
