### ISSUE TITLE
[Serializable] Classes

### ISSUE THREAD

**Issue by clambertus** [apache/lucenenet#275]
<p>In Lucene.Net 3.0.3 several classes were marked with the <span class="error">&#91;Serializable&#93;</span> attribute. The same has been done to several of the classes in the Lucene.Net (core), but most of the classes in the sub-projects are still not serializable.</p>

<p>Some of the legacy tests that were carried over required certain classes to be serializable (<a href="https://issues.apache.org/jira/browse/LUCENENET-170" title="BooleanClause serialization fails owing to issues with serializing Occur object" class="issue-link" data-issue-key="LUCENENET-170"><del>LUCENENET-170</del></a> and <a href="https://issues.apache.org/jira/browse/LUCENENET-338" title="Serialized queries function unreliably" class="issue-link" data-issue-key="LUCENENET-338"><del>LUCENENET-338</del></a>), which is how this issue was first discovered. </p>

<p>At the very least, all Queries, Filters, and Analyzers should be marked <span class="error">&#91;Serializable&#93;</span>, but it is unclear what criteria version 3.0.3 used to determine which other classes should be serializable. We need a clear strategy for this as well as the task to be done.</p>
<i>JIRA link - <a href="https://issues.apache.org/jira/browse/LUCENENET-574">[LUCENENET-574]</a> created by nightowl888</i>

**Comment by NightOwl888** [comment]
This was posted on the Lucene dev list today:

[Serializatio/Deserialization of Lucene objects like queries, sort fields etc](https://lists.apache.org/thread.html/r33078f97408ae5643d35a1bb6905959348f78c0f4d64f858e1bd47d8%40%3Cdev.lucene.apache.org%3E)

This seems to back up my previous statement about removing serialization from Lucene.NET classes, since that is the direction that Lucene has gone, as well.
