### ISSUE TITLE
RegexpQuery doesn't maintain any reference to the Regexp

### ISSUE THREAD

**Issue by 43081j** [apache/lucenenet#293]
We're using your parser to parse lucene queries as part of a conversion mechanism we have, so we traverse the AST in order to build up our own representation.

The one missing part right now is that a RegexpQuery does not give access to the original Regexp, or even the Term.

Lets say you have:

```cs
var ast = (RegexpQuery)parser.Parse("foo:/ab?def/", "all");
```

There seems to be no way to access `ab?def`, as a term, string or regexp. By this point, it has already been turned into an automaton and the original term has been thrown away or is in a protected property.

The parser should not make assumptions like this IMO. It is up to the consumer what we do with the AST, rather than forcing us to use your "automaton" representation. Would it be possible to somehow expose the untouched, original value of the query?

**Comment by NightOwl888** [comment]
As this is Lucene's design, not our own, we don't really have the latitude to make changes of this nature. We have been careful to preserve the accessibility of each class and member to match Lucene and to provide the same amount of extensibility in most cases.

That being said, as you have already discovered the "untouched, original value of the query" is already exposed as a protected `Term` property. I believe it was done this way because in Java it is possible to make "anonymous classes". For example, you could declare a new class inline that subclasses `RegexpQuery` in which the `Term` property would automatically be exposed. In C# you have to hand-roll a subclass, which makes it less convenient, but still exposes the same accessibility. Unfortunately, as the intent of the design is lost when converting code line by line, we can't really be sure of all of the places the Lucene designers intended to use "anonymous classes" that would potentially be suited for a better approach in .NET.

As for a deeper in-depth discussion of the reasoning behind the design, please contact the  [dk.brics.automaton authors](https://www.brics.dk/automaton/) or the [Lucene team](https://lucene.apache.org/core/discussion.html). 

FWIW, the internals of regular expression engines always throw away consumed characters by default and only capture if the regular expression engine supports it, such as with [capturing groups](https://www.regular-expressions.info/refcapture.html). If you are going to argue to support something like this, I would suggest arguing for a standardized capture of some kind rather than a one-off.

**Comment by 43081j** [comment]
In this case, this is not a regular expression engine, so I would have expected a regular expression query to be a representation of a "field" and a regular expression. It still seems a strange design since a parser should only really be responsible for parsing into a syntax tree. 

Either way what you say makes sense since you can't change the design. We can use a workaround for now.
