### ISSUE TITLE
Method 'get_properties' in ConfigurationBuilder does not have an impl. 

### ISSUE THREAD

**Issue by ensemblebd** [apache/lucenenet#311]
After upgrading from beta7 to **beta10**, I am now receiving an error:
```
System.TypeInitializationException: The type initializer for 'Lucene.Net.Diagnostics.Debugging' threw an exception. 
---> System.TypeInitializationException: The type initializer for 'Lucene.Net.Configuration.ConfigurationSettings' threw an exception. 
---> System.TypeLoadException: Method 'get_Properties' in type 'Lucene.Net.Configuration.ConfigurationBuilder' from assembly 'Lucene.Net, Version=4.0.0.0, Culture=neutral, PublicKeyToken=85089178b9ac3181' does not have an implementation.
   at Lucene.Net.Configuration.DefaultConfigurationFactory..ctor()
   at Lucene.Net.Configuration.ConfigurationSettings..cctor()
   --- End of inner exception stack trace ---
   at Lucene.Net.Configuration.ConfigurationSettings.GetConfigurationFactory()
   at Lucene.Net.Util.Properties.GetProperty[T](String key, T defaultValue, Func`2 conversionFunction)
   at Lucene.Net.Diagnostics.Debugging..cctor()
   --- End of inner exception stack trace ---
   at Lucene.Net.Analysis.Tokenizer.SetReader(TextReader input)
   at Lucene.Net.Analysis.Analyzer.GetTokenStream(String fieldName, TextReader reader)
   at Lucene.Net.Util.QueryBuilder.CreateFieldQuery(Analyzer analyzer, Occur operator, String field, String queryText, Boolean quoted, Int32 phraseSlop)
   at Lucene.Net.Util.QueryBuilder.CreateBooleanQuery(String field, String queryText, Occur operator)
```

I decompiled the .dll's to verify the class property exists. Support\Configuration\Base\ConfigurationBuilder.cs line 33.
Noticed in changelog for the versions many items were marked Internal instead of public.
But both `.Diagnostics.Debugging` and `.Configuration` namespaces are internal to the main `Lucene.Net` dll, so it couldn't possibly lack access, right? 
`Analysis.Common` is separate, but it's using a project ref so not sure how that could be improperly linked. 

I'm not quite sure how it's failing to resolve the `Properties` property via `DefaultConfigurationFactory`  during the constructors of the `StandardAnalyzer`, or `SimpleAnalyzer`.

Can anyone potentially point me in the right direction on this issue? Am at a grinding halt. 

*Edit: 
Can confirm beta9 introduces the problem for me. Beta 8 works fine. Investigating...

**Comment by NightOwl888** [comment]
Thanks for the report.

I was able to reproduce this. It is only happening on .NET Framework and only if you are using `Microsoft.Extensions.Configuration` higher than version 1.1.2 within your project. For compatibility reasons, we reference `Microsoft.Extensions.Configuration.Abstractions` version 1.1.2 in .NET Framework, since higher versions only support .NET Framework 4.6.1 and higher.

There was a breaking change introduced in `IConfigurationBuilder` between `Microsoft.Extensions.Configuration.Abstractions` version 1.1.2 and version 2.0.0 where `IConfigurationBuilder.Properties` was changed from `Dictionary<string, object>` to `IDictionary<string, object>` so the `DefaultConfigurationFactory` currently requires you to use components from `Microsoft.Extensions.Configuration` version 1.1.2 on .NET Framework.

If downgrading `Microsoft.Extensions.Configuration` is not an option, then you must downgrade to `Lucene.Net` version 4.8.0-beta-00008.

We need to get rid of the `IConfigurationBuilder` implementation to fix this problem, as the only requirement we have internally is to implement `IConfiguration` to provide a logical default that reads system variables. Unfortunately, this issue is also preventing .NET Framework users from providing their own `IConfigurationFactory` implementation to override because the exception occurs in the initialization before an alternative implementation can be set.

**Comment by ensemblebd** [comment]
Thank you so much!!

**Comment by Plexois37** [comment]
I'm using Beta 16 and it I have the same issue.
I also use the .Net Framework but using version 1.1.2 of Microsoft.Extensions.Configuration and Microsoft.Extensions.Configuration.Abstractions doesn't change anything.

**Comment by NightOwl888** [comment]
Unless you are seeing the same exception, this is probably due to a versioning conflict between Lucene.NET's reference to this package and another library's reference to it. Please review the output of each of your projects and pay close attention to the version of all Microsoft.Extensions.Configuration libraries in each `bin` folder. If it is not consistently outputting the same version for each of your projects, you may need to add a reference to the offending package in order to explicitly force a version upgrade (assuming the conflict is not due to something you own).

Here is a simple console app to automate the process of checking for conflicts that you can adjust to check your projects.

```c#
            // Build the project in debug mode before running

            var configuration = "Release";
            var targetFramework = "net461";
            var fileToFind = "Microsoft.Extensions.Configuration.Abstractions.dll";
            var baseFolder = @"<path to the root of your source code>";

            foreach (string file in Directory.EnumerateFiles(baseFolder, "*.dll", SearchOption.AllDirectories)
                .Where(f => Path.GetDirectoryName(f).EndsWith(@$"bin\{configuration}\{targetFramework}")))
            {
                if (Path.GetFileName(file) == fileToFind)
                {
                    var assemblyName = AssemblyName.GetAssemblyName(file);

                    Console.WriteLine(assemblyName.ToString() + " - " + file);
                }
            }
```

If you square up your references and still see an exception, please open a new bug report with a repro project.
