### ISSUE TITLE
Upgrading a .Net Framework 4.7.2 project using NuGet

### ISSUE THREAD

**Issue by tmc101** [apache/lucenenet#317]
Hi

I'm trying to upgrade a .NET Framework 4.7.2 class library project from Lucene.Net 3.0.3 to 4.8.0-beta00011.

The NuGet package manager dependencies in Visual Studio 2017 shows:

![image](https://user-images.githubusercontent.com/11647741/88550186-29119780-d019-11ea-9621-99ecb5625309.png)

However, when I go ahead with the update, the installed dependencies are:

![dependencies](https://user-images.githubusercontent.com/11647741/88550349-66762500-d019-11ea-8151-eb386d419f3c.PNG)

Is that expected?

The extra dependencies seem to have been included since 4.8.0-beta00009 as 4.8.0-beta00008 shows only J2N as a dependency:

![image](https://user-images.githubusercontent.com/11647741/88550695-dedce600-d019-11ea-93ac-23a46d817cf2.png)

**Comment by NightOwl888** [comment]
Yes, this is expected behavior, as the target we are currently using for .NET Framework is `net45`. Unfortunately, newer versions of `Microsoft.Extensions.Configuration.Abstractions` only support `net461` so we had to reference version 1.1.2 on .NET Standard 1.1.

However, there is an easy workaround. Since we are not constraining the version, simply install the latest [`Microsoft.Extensions.Configuration`](https://www.nuget.org/packages/Microsoft.Extensions.Configuration.Abstractions/3.1.6) version 3.1.6 before you install Lucene.Net, then it won't install any of the .NET Standard 1.x dependencies since a compatible version will already exist in your project.

**Comment by tmc101** [comment]
Thanks.

The workaround worked - but now I'm seeing:

![image](https://user-images.githubusercontent.com/11647741/88565330-53208500-d02c-11ea-83b1-0cbf83009f44.png)

This seems to be #286 - I'll wait to see what happens there.
