### ISSUE TITLE
Beta nuget packages confusion

### ISSUE THREAD

**Issue by jregnier** [apache/lucenenet#318]
I'm confused about the Nuget package versions, currently, I'm 4.8.0-beta00008 but when I click on the Include prerelease I see that I'm a few versions behind and that I could install version 4.8.0-beta00011. On the main download page, it goes up to 4.8.0-beta00009. So is version 4.8.0-beta00011 legit release or is it some kind of pre pre release.

Thanks

**Comment by NightOwl888** [comment]
We apologize for the confusion. The releases are legitimate, it is just that there are still several manual steps with releasing the documentation, so it has fallen a bit behind. The list of changes can be found on the [releases page](https://github.com/apache/lucenenet/releases). We haven't had many new features in awhile, we are mainly focused on improving performance, and have [doubled search speed since 4.8.0-beta0007](https://github.com/apache/lucenenet/pull/310#issuecomment-661002167).

4.8.0-beta00011 was an unplanned release to fix a bug introduced in 4.8.0-beta00009 that affects .NET Framework users that have `Microsoft.Extensions.Configuration.Abstractions` higher than 1.1.2 installed in their project.

**Comment by jregnier** [comment]
Thanks for the reply. That's perfect, doubled the speed!! that's extremely exciting.

**Comment by Shazwazza** [comment]
FYI I've also just published the download pages for beta00010 and beta00011: https://lucenenet.apache.org/download/download.html (just needs a ctrl + f5 refresh).
