### ISSUE TITLE
Lucene.Net NuGet (4.8.0-beta00013) does not compile under Visual 2017 - Lucene.Net.CodeAnalysis.Lucene1000_TokenStreamOrItsIncrementTokenMethodMustBeSealedCSAnalyzer

### ISSUE THREAD

**Issue by Xebast** [apache/lucenenet#394]
Hi,

I encountered issue integrating Lucene.Net NuGet (4.8.0-beta00013) in a .Net Standard 2.0 assembly.
My builder is VS2017. 

I reproduced it in simple project. 
Just creating a .Net Standard 2.0 Library; here is csProj content 
[LuceneClient.zip](https://github.com/apache/lucenenet/files/5590952/LuceneClient.zip) : 

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Lucene.Net" Version="4.8.0-beta00013" />
    <PackageReference Include="Lucene.Net.Analysis.Common" Version="4.8.0-beta00013" />
    <PackageReference Include="Lucene.Net.QueryParser" Version="4.8.0-beta00013" />
  </ItemGroup>
  <PropertyGroup>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsAsErrors />
  </PropertyGroup>
</Project>
```

_Error CS8032 An instance of analyzer Lucene.Net.CodeAnalysis.Lucene1000_TokenStreamOrItsIncrementTokenMethodMustBeSealedCSAnalyzer cannot be created from C:\Users\sebastien\.nuget\packages\lucene.net\4.8.0-beta00013\analyzers\dotnet\cs\Lucene.Net.CodeAnalysis.CSharp.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=3.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.._	

The compilation error is related to TreatWarningsAsErrors == true.
Of course, I can Add `<NoWarn>CS8032</NoWarn>` to csproj items. But unfortunately, if another assemblie uses this simple project, it has also to add this NoWarn atribute; so difficult to maintain later.

I checked #286 but this fix seems to be integrated in version I use (beta00013)

Note that it does NOT occur VS2019 (business assembly and simple project above); but I cannot use 2019 for the moment.

Thanks for your help.

**Comment by NightOwl888** [comment]
Thanks for the report.

I suspect that VS2017 requires .NET Framework < 4.6.1 or .NET Standard 1.x in order for the Analyzers to function. Unfortunately, there doesn't seem to be any documentation on how to create a multi-targeted VS analyzer package, so the simplest course of action is to use a single target. Currently, we are targeting .NET Standard 2.0 because that is the version the [latest `Microsoft.CodeAnalysis.CSharp.Workspaces` package targets](https://www.nuget.org/packages/Microsoft.CodeAnalysis.CSharp.Workspaces).

It is [Microsoft's recommendation to target .NET Standard 2.0 where possible and discontinue using .NET Standard 1.x](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#which-net-standard-version-to-target) because of the number of extra dependencies in .NET Standard 1.x. However, I noticed that [Xunit.Analyzers is targeting .NET Standard 1.3](https://github.com/xunit/xunit.analyzers/blob/main/src/xunit.analyzers/xunit.analyzers.csproj) and [StyleCop is targeting .NET Standard 1.1 and .NET Framework 4.5.2](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/3c877565bcfeae0e737158d7c5a7092a87ef9186/StyleCop.Analyzers/StyleCop.Analyzers/StyleCop.Analyzers.csproj), although the only assembly that is shipped via NuGet is .NET Standard 1.1. This would seem to confirm my suspicion that .NET Standard 1.x is required for multi-targeting VS2017 and VS2019.

So, basically I believe the fix for VS2017 support will be:

1. Change the `TargetFramework` of [`Lucene.Net.CodeAnalysis.CSharp`](https://github.com/apache/lucenenet/blob/8ad48e7ef73c62390fc1c8f2b6ca66d60eec44a8/src/dotnet/Lucene.Net.CodeAnalysis.CSharp/Lucene.Net.CodeAnalysis.CSharp.csproj#L25) and [`Lucene.Net.CodeAnalysis.VisualBasic`](https://github.com/apache/lucenenet/blob/8ad48e7ef73c62390fc1c8f2b6ca66d60eec44a8/src/dotnet/Lucene.Net.CodeAnalysis.VisualBasic/Lucene.Net.CodeAnalysis.VisualBasic.csproj#L25) to `netstandard1.3`.
2. Change the [target version](https://github.com/apache/lucenenet/blob/8ad48e7ef73c62390fc1c8f2b6ca66d60eec44a8/build/Dependencies.props#L46-L47) of `Microsoft.CodeAnalysis.CSharp.Workspaces` and `Microsoft.CodeAnalysis.VisualBasic.Workspaces` to < 3.0.0.

(unconfirmed)

We would be happy to accept a PR with these changes or to discuss alternatives if this isn't a fix.

## Disabling Analyzers

According to the documentation, [analyzers can be disabled for dependent projects](https://docs.microsoft.com/en-us/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2019#dependent-projects). So, I suggest adding the following to your project to see if it stops the dependent projects from requiring the analyzers, also. Let us know whether this setting is helpful.

```xml
<PackageReference Include="Lucene.Net" Version="4.8.0-beta00013" PrivateAssets="all" />
```

Note that the `Lucene.Net` NuGet package is the only one with code analyzers in it.
