### ISSUE TITLE
Migrating from lucene.net 3.0 to 4.8

### ISSUE THREAD

**Issue by PaulVrugt** [apache/lucenenet#398]
We are upgrading from lucene.net 3.0 to 4.8. Now we have some issues because of breaking changes between these versions. 

1. In our project, we make use of the `CustomScoreQuery` which used to be part of the `Lucene.Net.Search.Function` namespace. It is no longer there. According to the [Apache documentation][1] is is deprecated and should be replaced by using the `FunctionScoreQuery`, but this class doesn't seem to exist in 4.8. What should we use instead?

2. We used a custom collector class, that inherited from `Lucene.Net.Search.Collector`. In 4.8, this class has become sealed. I see there a several implementation classes. Which one should I use?
    *I discovered I need to use the `ICollector` interface. Which partly solves the problem. In the `SetNextReader` function, we use to do something like `Lucene.Net.Search.FieldCache_Fields.DEFAULT.GetStrings(reader, "<field>")`. This has also been removed. Apparently we need to use `Lucene.Net.Search.FieldCache.DEFAULT.GetTerms(context.AtomicReader, "<fieldid>", false)`. So this issue seems solved*

3. We used a class that inherited from `CustomScoreProvider` in `Lucene.Net.Search.Function`, but it is no longer there in 4.8. We used it combined with the `CustomScoreQuery` as returnvalue for the `GetCustomScoreProvider` method There doesn't seem to be any alternative. What should we use instead?

4. We used a WhitespaceAnalyzer in 3.0, Which doesn't seem to be there anymore. What is the replacement for that?

There is [some documentation][2], but unfortunately the link to the migration guide is still a TODO.

  [1]: https://lucene.apache.org/core/7_4_0/queries/org/apache/lucene/queries/CustomScoreQuery.html
  [2]: https://lucenenet.apache.org/docs/4.8.0-beta00013/

**Comment by NightOwl888** [comment]
Documentation is still a work in progress, and updating it for .NET is currently blocked until #396 is completed.

> In our project, we make use of the CustomScoreQuery which used to be part of the Lucene.Net.Search.Function namespace. It is no longer there. According to the Apache documentation is is deprecated and should be replaced by using the FunctionScoreQuery, but this class doesn't seem to exist in 4.8. What should we use instead?

> We used a class that inherited from CustomScoreProvider in Lucene.Net.Search.Function, but it is no longer there in 4.8. We used it combined with the CustomScoreQuery as returnvalue for the GetCustomScoreProvider method There doesn't seem to be any alternative. What should we use instead?

[CustomScoreQuery](https://lucenenet.apache.org/docs/4.8.0-beta00013/api/queries/Lucene.Net.Queries.CustomScoreQuery.html) and [CustomScoreProvder](https://lucenenet.apache.org/docs/4.8.0-beta00013/api/queries/Lucene.Net.Queries.CustomScoreProvider.html) are still there, but the project has been split into [26 specialized assemblies](https://github.com/apache/lucenenet#all-packages-1) rather than having everything in one assembly. You just need to reference the [Lucene.Net.Queries](https://www.nuget.org/packages/Lucene.Net.Queries/) package.

> We used a WhitespaceAnalyzer in 3.0, Which doesn't seem to be there anymore. What is the replacement for that?

[WhiteSpaceAnalyzer](https://lucenenet.apache.org/docs/4.8.0-beta00009/api/analysis-common/Lucene.Net.Analysis.Core.WhitespaceAnalyzer.html) is in the [Lucene.Net.Analysis.Common](https://www.nuget.org/packages/Lucene.Net.Analysis.Common/) package.

**Comment by PaulVrugt** [comment]
@NightOwl888  Thanks! That clarifies a lot and solves a lot of migration issues! Might I ask some follow up questions?

1. we used to create indexwriters by calling:
`new Index.IndexWriter(_luceneDir, analyzer, False, Index.IndexWriter.MaxFieldLength.UNLIMITED)`
now I found we need to use the config object instead of separate parameters in the new situation. So we do somthing like:

````
var config = new Index.IndexWriterConfig(Util.LuceneVersion.LUCENE_48, analyzer) {OpenMode = Index.OpenMode.APPEND}
New Index.IndexWriter(_luceneDir, config)
````

where do we leave the max field length here? Is it still required?

2. Where did the `Optimize` method of the IndexWriter go? Is there any alternative?
3. We used to use fields like:
    `New Documents.Field("title", "<value>", Documents.Field.Store.YES, Documents.Field.Index.ANALYZED)`

    now the obsolete error tells me I need to use `StringField` or `TextField`. Which of the two do I need to use, and how to I pass 
    the `Store` and `Analyzed` properties to them?

4. The FieldCache `GetStrings` method was replace by `GetTerms`, but `GetTerms` requires an `AtomicReader`, we used to be able to pass an `IndexReader` into this method and it used to return a string array containing the values. How to I get the same kind of behavior from the `GetTerms` method?

Sorry about the interrogation, but we really want to migrate, but the the lack of migration documentation makes it really hard.

**Comment by jeme** [comment]
@NightOwl888 maybe the new Github discussion feature should be enabled as it's more suitable for things like this i guess :) ?

Just to give a quick answer to two of them.

> 1. Where did the `Optimize` method of the IndexWriter go? Is there any alternative?
Even in 3.0.3 the general consensus was that you shouldn't call that method but instead let Lucene handle optimizations internally. It generally knows better.

> 2. We used to use fields like:
>    `New Documents.Field("title", "<value>", Documents.Field.Store.YES, Documents.Field.Index.ANALYZED)`
>    now the obsolete error tells me I need to use `StringField` or `TextField`. Which of the two do I need to use, and how to I pass
>    the `Store` and `Analyzed` properties to them?

You can still specify store as an option, As for Analyzed, AFAIK.
TextField => Analyzed
StringField => Not Analyzed

So you should use TextField in your case.
```
new TextField(fullpath, transform(self.DeserializedValue), Field.Store.NO)
```

The other two I will leave to @NightOwl888 , maybe he can also elaborate further.

**Comment by NightOwl888** [comment]
> Sorry about the interrogation, but we really want to migrate, but the the lack of migration documentation makes it really hard.

The migration guide is here: [Apache Lucene Migration Guide (4.8.0)](https://lucene.apache.org/core/4_8_0/MIGRATE.html). Thanks for bringing this to our attention, it hasn't been added to our API docs, so I opened #399.

Most of the answers to your questions can be found in the migration guide. However, do note that some method names were changed to follow .NET conventions (for example `.terms()` was renamed `.GetTerms()`, `.iterator()` has been changed to `.GetEnumerator()`, members with numeric type names have also been renamed `Int` > `Int32`, `Long` > `Int64`, `Float` > `Single`, etc.)

> Where did the Optimize method of the IndexWriter go? Is there any alternative?

Many people abused the method because it was poorly named. Its purpose (when used correctly) is to rewrite an index to a smaller number of segments. However, many people called it with no arguments immediately after creating their index, which *rewrites* the entire index that was just written to a single segment.

The method has been renamed to `ForceMerge()` to clarify what it does and prevent it from being irresistible to call when it is not appropriate to.

[Simon says: optimize is bad for you….](https://blog.trifork.com/2011/11/21/simon-says-optimize-is-bad-for-you/)

**Comment by PaulVrugt** [comment]
@jeme @NightOwl888  you guys rock! Thanks for the input. I've taken a look at the migration guide, and this answers all of my questions posted here but one:

(see question 1 from https://github.com/apache/lucenenet/issues/398#issuecomment-741691266) In 3.0.3, we called `new Index.IndexWriter(_luceneDir, analyzer, False, Index.IndexWriter.MaxFieldLength.UNLIMITED)`
We don't seem to have any method to pass the MaxFieldLength property to the new `IndexWriter`, has it become obsolete and can I simply ignore it?

Hopefully you can provide me with an answer to this, and I'll get out of your hair.

**Comment by NightOwl888** [comment]
> @NightOwl888 maybe the new Github discussion feature should be enabled as it's more suitable for things like this i guess :) ?

@jeme 

Good idea. However, Apache doesn't give us access to all of the settings, only the ones that are enabled through [.asf.yaml](https://cwiki.apache.org/confluence/display/INFRA/git+-+.asf.yaml+features#git.asf.yamlfeatures-Upcomingfeatures). They don't have discussions listed as a feature:

```yaml
github:
  features:
    # Enable wiki for documentation
    wiki: true
    # Enable issue management
    issues: true
    # Enable projects for project management boards
    projects: true
```

However, I have added a question to that page asking if they can enable/add it.

**Comment by NightOwl888** [comment]
> In 3.0.3, we called new Index.IndexWriter(_luceneDir, analyzer, False, Index.IndexWriter.MaxFieldLength.UNLIMITED)
We don't seem to have any method to pass the MaxFieldLength property to the new IndexWriter, has it become obsolete and can I simply ignore it?

From https://lucene.apache.org/core/3_6_2/api/all/org/apache/lucene/index/IndexWriter.MaxFieldLength.html:

### Deprecated. 
*use [LimitTokenCountAnalyzer](https://lucenenet.apache.org/docs/4.8.0-beta00013/api/analysis-common/Lucene.Net.Analysis.Miscellaneous.LimitTokenCountAnalyzer.html) instead.*

**Comment by PaulVrugt** [comment]
Well thank you. You've been a great help, and will probably soon have one more ISV with over a million end users using lucene.net 4.8 for searching!
