### ISSUE TITLE
QueryParser.Parse Error if Phrase Ends with Capitalized Conjunction

### ISSUE THREAD

**Issue by codystott** [apache/lucenenet#400]
I was able to reproduce this with the following code:
````
LuceneVersion AppLuceneVersion = LuceneVersion.LUCENE_48;
QueryParser queryParser = new QueryParser(AppLuceneVersion, "name", new ClassicAnalyzer(AppLuceneVersion));
queryParser.Parse("test AND");
````

Lucene.Net.QueryParsers.Classic.ParseException
  HResult=0x80131500
  Message=Cannot parse 'test AND': Encountered "<EOF>" at line 1, column 8.
Was expecting one of:
    <NOT> ...
    "+" ...
    "-" ...
    <BAREOPER> ...
    "(" ...
    "*" ...
    <QUOTED> ...
    <TERM> ...
    <PREFIXTERM> ...
    <WILDTERM> ...
    <REGEXPTERM> ...
    "[" ...
    "{" ...
    <NUMBER> ...
    <TERM> ...
    "*" ...
    
  Source=Lucene.Net.QueryParser
  StackTrace:
   at Lucene.Net.QueryParsers.Classic.QueryParserBase.Parse(String query)
   at LuceneSpecialCharTest.Program.Main(String[] args) in C:\Projects\LuceneSpecialCharTest\Program.cs:line 29

  This exception was originally thrown at this call stack:
	Lucene.Net.QueryParsers.Classic.QueryParser.Jj_consume_token(int)
	Lucene.Net.QueryParsers.Classic.QueryParser.Clause(string)
	Lucene.Net.QueryParsers.Classic.QueryParser.Query(string)
	Lucene.Net.QueryParsers.Classic.QueryParser.TopLevelQuery(string)
	Lucene.Net.QueryParsers.Classic.QueryParserBase.Parse(string)

Inner Exception 1:
ParseException: Encountered "<EOF>" at line 1, column 8.
Was expecting one of:
    <NOT> ...
    "+" ...
    "-" ...
    <BAREOPER> ...
    "(" ...
    "*" ...
    <QUOTED> ...
    <TERM> ...
    <PREFIXTERM> ...
    <WILDTERM> ...
    <REGEXPTERM> ...
    "[" ...
    "{" ...
    <NUMBER> ...
    <TERM> ...
    "*" ...

**Comment by NightOwl888** [comment]
The [Query Syntax Documentation](https://lucenenet.apache.org/docs/4.8.0-beta00013/api/queryparser/Lucene.Net.QueryParsers.Classic.html#classes) states:

> ### ParseException
>
> This exception is thrown when parse errors are encountered. You can explicitly create objects of this exception type by calling the method `GenerateParseException` in the generated parser.
>
> You can modify this class to customize your error reporting mechanisms so long as you retain the public fields.

It is expected behavior for a malformed query to throw an exception, as this is a line-by-line port from Java.

That said, in .NET it would be ideal if we had a `TryParse()` method that returned a boolean and an error message, but that would need to be done consistently on all of the Query Parsers, not just the Classic one. There are other things to consider redesigning, such as culture and other configuration as parameters of `Parse()/TryParse()` instead of public properties. However, I am not sure if any of that will make it into the 4.8.0 release.

**Comment by NightOwl888** [comment]
Do note that if you are expecting the Query Parser to never throw an exception regardless of how poorly constructed the query is, there is a [Simple](https://lucenenet.apache.org/docs/4.8.0-beta00013/api/queryparser/Lucene.Net.QueryParsers.Simple.html) QueryParser made for this purpose.

> Any errors in query syntax will be ignored and the parser will attempt to decipher what it can; however, this may mean odd or unexpected results.

**Comment by NightOwl888** [comment]
I am closing this issue, as it seems that either using a valid query string or using the `SimpleQueryParser` will salve the issue.
