### ISSUE TITLE
Determine why Term is null in TestDocTermOrds when using SeekExact(0)

### ISSUE THREAD

**Issue by NightOwl888** [apache/lucenenet#405]
[This change](https://github.com/apache/lucenenet/pull/381/commits/c95ac72b2a50dd4d5fc887003df82bc6e2db1fb7) diverges from Java Lucene and shouldn't be necessary.

We run tests in `Release` mode with `Verbose` set to `false`, so in that case the problem is skipped. However, in `Debug` mode the problem crops up. We need to investigate why `Term` is sometimes `null` and formulate a fix.

**Comment by NightOwl888** [comment]
I suspect that https://github.com/apache/lucenenet/commit/1fed4fb2c8d37cdca9171d30a01c26cd3035134d might be where this problem began occurring.

**Comment by rclabo** [comment]
I'll do this one

**Comment by NightOwl888** [comment]
Great. I have assigned the issue to you. Thanks.

**Comment by rclabo** [comment]
It seems like the commit for [this change](https://github.com/apache/lucenenet/pull/381/commits/c95ac72b2a50dd4d5fc887003df82bc6e2db1fb7) got rolled back since it does not appear in the [commit history for TestDocTermOrds](https://github.com/apache/lucenenet/commits/master/src/Lucene.Net.Tests/Index/TestDocTermOrds.cs).  Is that a valid understanding?  If so, is there any way in GitHub to actually confirm the commit was applied on date A but rolled back on date B? Or is there some other explanation for not seeing that commit in the commit history?  (Sorry for these kinds of basic questions, I'm still working on better understanding GitHub )

**Comment by NightOwl888** [comment]
I apologize, I should have specified that the change is from PR #381 that hasn't been merged to `master`.
