### ISSUE TITLE
HunspellStemFilter does not work with zero affix

### ISSUE THREAD

**Issue by SergeyKotyushkin** [apache/lucenenet#419]
Hello!

Our hunspell aff file contains some rules for suffixes and prefixes that have in affix 0 value.
For example:
_aff file_
```
SET UTF-8
TRY esianrtolcdugmphbyfvkwzESIANRTOLCDUGMPHBYFVKWZ’

FLAG long

SFX AA Y 1
SFX AA er 0 er
```

_dic file_
```
1
worker/AA
```

So if the `work` word is analyzed then the `worker` word must be returned.
But returns `work` - the rule does not apply.

The reason is the value of the affix 0, because changing the rule fixes the analysis:
```
SFX AA ker k er
```

I found in [code](https://github.com/apache/lucenenet/blob/f5cca0b1a7c855f2fe44a5cdd27763aab7acdf22/src/Lucene.Net.Analysis.Common/Analysis/Hunspell/Dictionary.cs#L459) a todo about zero-affix handling fix. But I don't understand if this todo relates to my problem or it is another one problem.

If this the same problem could you tell me there is a plan to fix it soon?

**Comment by NightOwl888** [comment]
Thanks for the report.

This is a known issue with Lucene 4.8.0 that was fixed in [LUCENE-5817](https://issues.apache.org/jira/browse/LUCENE-5817) in  and then patched again in [LUCENE-5840](https://issues.apache.org/jira/browse/LUCENE-5840) in Lucene 4.10.

While strictly speaking we are supposed to leave the limitations in place of 4.8.0, we are making some exceptions in places where usability is a factor, especially in cases where there is no reasonable way to use inheritance to fix the issue. In this case, I would approve the changes provided the tests all pass and there are no ill effects produced by adding the patch out of order.

That being said, we are trying to make as straight of a line as possible to the 4.8.0 release. As such, these "extra" changes are something we probably won't make the extra effort to do. However, we will include them if a PR is submitted by the community.

**Comment by rclabo** [comment]
I'll do this one.  It can be assigned to me.

**Comment by rclabo** [comment]
I've spent some time working on this and unfortunately it's a lot bigger than it first appears.  

On the surface it requires two patches: LUCENE-5817 & LUCENE-5840.  But those patches were made to Lucene 4.10 files, and when investigating other patches that just one of the patched files ([hunspell/Dictionary.java](https://github.com/apache/lucene-solr/blame/releases/lucene-solr/4.10.0/lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/Dictionary.java) ) contains, I learned that it contained the following patches that occurred after Lucene 4.8.1:  LUCENE-5485, LUCENE-5603, LUCENE-5777, LUCENE-5778, LUCENE-5823, LUCENE-5826, and LUCENE-5864.   

That was almost enough of a deterrent for me right there.  But I figured if most of those patches were only to the same small set of files, maybe applying all of them was still doable.  But unfortunately "LUCENE-5778: support hunspell morphological description fields", has 20 changed files associated with it.  Changes of that scale out of sync from when they were originally applied (i.e. applying them to 4.8.1 when they were not applied until 4.10) feels pretty risky to me.  And one would need to check for missing patches in those 20 files as well, as well as the other files affected by the other patches I listed above.  

This feels too big to do now, at least for me.

**Comment by NightOwl888** [comment]
Thanks. I took a close look at these patches.

My first thought was that since most analyzers exist in a vacuum, to upgrade hunspell to the latest version of Lucene. However, FST had some major changes in 6.x, so that is not an option.

But since there were quite a few hunspell issues patched before 5.x, I am proposing upgrading the whole `Lucene.Net.Hunspell` namespace (and tests) to version [4.10.4](https://github.com/apache/lucene-solr/tree/releases/lucene-solr%2F4.10.4), the latest 4.x version. This reduces the risk of incompatible changes and gives us a point in time we can debug the code against without too much mental anguish, if necessary.

"LUCENE-5778: support hunspell morphological description fields" isn't a big deal, but "LUCENE-5864: Split BytesRef into BytesRef and BytesRefBuilder" is a major API change to the `Lucene.Net.Util` namespace. That being said, it is not a necessary piece of the puzzle - we just need to "downgrade" the following classes appropriately.


When Lucene 4.10 Uses  |  Replace With
-- | --
`BytesRefBuilder`  |  `BytesRef`
`CharsRefBuilder`  |  `CharsRef`
`IntsRefBuilder` | `Int32sRef`
`LongsRefBuilder` | `Int64sRef`

Thoughts?

**Comment by rclabo** [comment]
I think that's a reasonable approach if some from the community wants to contribute it.  Otherwise I vote we pick up this functionality once we jump from 4.8 to the latest version of Lucene. I'd prefer to focus our limited resources on getting 4.8 to release stage rather than incorporating features that came after 4.8.

**Comment by NightOwl888** [comment]
We are releasing 4.8.0, which is not the most stable 4.x version. Hunspell was buggy until at least 4.10, primarily it seems because there is no offficial spec for it so it took some exploration to make it work. So, we have 3 choices.

1. Strictly follow Lucene 4.8.0 including all of its bugs.
2. Patch Lucene 4.8.0 in some regards to make it less buggy.
3. Plan to release 4.10.4 before moving on to 8.x.

IMO, since we have a long road to get to 8.x we should leave stable software in our wake. So, that either means patching some parts of 4.8.0 to eliminate known bugs or doing a full upgrade of the whole project to 4.10.4 before moving on to 8.x. Clearly, of the two options the patch is simpler.
