### ISSUE TITLE
How to get values for subparts of Heiarchial facet

### ISSUE THREAD

**Issue by yashhema** [apache/lucenenet#491]
Hello,
In SimpleFacetsExample , we have a facet -- "Publish Date" and we have set it to 
config.SetHierarchical("Publish Date", true);

Example data we are indexing is -- new FacetField("Publish Date", "2010", "10", "15")

If I do search where ("Publish Date","2010")  -- I get the result ; but I am not able to find a way to find how many counts are there for month =10 and day =15

Can you please suggest how can i get that

**Comment by NightOwl888** [comment]
Hi there. Sometimes people answer user help queries on GitHub, but since nobody replied let me suggest one of the following options:

- [StackOverflow](https://stackoverflow.com/questions/tagged/lucene.net) (be sure to add both the <c>lucene.net</c> and <c>lucene</c> tags) 
- [Lucene.NET mailing lists](https://lucenenet.apache.org/contributing/mailing-lists.html)
- [Lucene mailing lists](https://lucene.apache.org/core/discussion.html)
