### ISSUE TITLE
The given key 'Lucene.Net.Support.WeakDictionary`2+WeakKey`1[System.Object,System.Collections.Generic.IDictionary`2[Lucene.Net.Search.FieldCacheImpl+CacheKey,System.Object],System.Object]' was not present in the dictionary.

### ISSUE THREAD

**Issue by hamzashoukat94** [apache/lucenenet#604]
```

 Sort sort = new Sort(new SortField("Category2", SortFieldType.STRING_VAL));
 TopFieldDocs fields = searcher.Search(query, filter, TOTAL_ITEMS, sort, true, false);


```
I'm executing the above mentioned code. This is giving me exception stating that 
`The given key 'Lucene.Net.Support.WeakDictionary`2+WeakKey`1[System.Object,System.Collections.Generic.IDictionary`2[Lucene.Net.Search.FieldCacheImpl+CacheKey,System.Object],System.Object]' was not present in the dictionary.`

I debugged the LuceneNet 4.8 code. And I found the particular faulty code is in WeakDictionary.cs line no 156:165.
```
  public TValue this[TKey key]
        {
            get => _hm[new WeakKey<TKey>(key)]; 
            set
            {
                CleanIfNeeded();
                _hm[new WeakKey<TKey>(key)] = value;
            }
        }

```
Kindly update the issue asap.

**Comment by NightOwl888** [comment]
Thanks for the report.

Could you please provide a complete example that we can run to reproduce the issue?

`WeakDictionary` doesn't tell us anything other than that you are using .NET Framework. Unfortunately, Microsoft didn't expose the enumerator of `ConditionalWeakTable` until .NET Standard 2.1, so we are left without a reasonable alternative. `WeakDictionary` is just a workaround for .NET Framework.

Do note that it is not supposed to keep references internally for any objects that are put in it. You have to hold onto the references from outside of the application (assuming that you are adding them explicitly), otherwise there is no guarantee that they will be retrievable.

**Comment by hamzashoukat94** [comment]
Thanks for the quick response and I'm expecting quick response till further. 
Steps to reproduce it:
1. Initialize Lucene Directory and IndexWriter.
2. Build Index e.g 1000 Documents.
3. Run the below mention code. 
4. In result of step 3, you will get the reported issue. 
```
               if (!analyzer.GetType().Equals(new WhitespaceAnalyzer(version).GetType()))
                    filterTerm = filterTerm.ToLower();

                Filter filter = new QueryWrapperFilter(new TermQuery(new Term(fieldName, filterTerm)));

                QueryParser parser = new QueryParser(version, fieldName, analyzer);
                Query query = parser.Parse(searchTerm);

                Sort sort = new Sort(new SortField("Category2", SortFieldType.STRING_VAL));

                TopFieldDocs fields = searcher.Search(query, filter, TOTAL_ITEMS, sort, true, false);

                if (fields.MaxScore > 0)
                    throw new Exception(fields.MaxScore + " is returned as MaxScore however it was marked false.");

                ScoreDoc[] docsFound = fields.ScoreDocs;
```

**Comment by hamzashoukat94** [comment]
I fixed this issue in this PR #605

**Comment by NightOwl888** [comment]
I have searched the entire codebase and the getter for `WeakDictionary<TKey, TValue>` isn't called anywhere. So, the only way this can fail is if you are using a copy of `WeakDictionary<TKey, TValue>` in your own code (since it is marked internal).

If you need a weak dictionary in your own code, please use [`ConditionalWeakTable<TKey, TValue>`](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.conditionalweaktable-2) instead. The only reason we use `WeakDictionary<TKey, TValue>` is because the enumerator API wasn't exposed on `ConditionalWeakTable<TKey, TValue>` in .NET Framework and .NET Standard 2.0. Many use cases don't require enumeration. But if you need enumeration, I would recommend upgrading to .NET Core rather than copying our substandard workaround into your project.

Note there is no `this[index]` property on `ConditionalWeakTable<TKey, TValue>`, to get a single value, you must call `TryGetValue()` instead, which is what we are doing throughout the codebase on `WeakDictionary<TKey, TValue>`. But `WeakDictionary<TKey, TValue>` must always be used with locking to make it threadsafe, which is one of many reasons why we haven't exposed it as public.

**Comment by hamzashoukat94** [comment]
Issue fixed with the latest commit.
