### ISSUE TITLE
MMapDirectory leads the process to high memory. 

### ISSUE THREAD

**Issue by hamzashoukat94** [apache/lucenenet#608]
I'm facing the issue of high memory because of **MMapDirectory**. In my scenario, I'm opening **100 directories and writers respectively** for 100 different indexes. After writing around 1 million documents, the process reaches around **35 GB**. I took the dump of that process, after analysis of that dump. I found that there is a lot of memory consumption because of MMapDirectory. 

I'm expecting a quick response.

**Comment by NightOwl888** [comment]
`MMapDirectory` is a wrapper around the [`MemoryMappedFile` class](https://docs.microsoft.com/en-us/dotnet/api/system.io.memorymappedfiles.memorymappedfile?view=net-6.0), and is meant to keep some data in RAM for fast read access. If you are only writing, you might be better off using [`NIOFSDirectory`](https://lucenenet.apache.org/docs/4.8.0-beta00015/api/core/Lucene.Net.Store.NIOFSDirectory.html) or [`SimpleFSDirectory`](https://lucenenet.apache.org/docs/4.8.0-beta00015/api/core/Lucene.Net.Store.SimpleFSDirectory.html) instead. Have you tried either of these?

Note that the documentation may not be correct about the performance characteristics of these directories, as some of the information is still referring to issues that occur in Java (so they don't necessarily apply in .NET).

**Comment by eladmarg** [comment]
Memory Mapped Files allow to you fast random access to file content.
this is done by letting the OS to manage what's to keep in ram. this memory also can be free quite fast

if you have free memory, most of the time you want to get the most of it, and use it. (that's why you paid for it)
so high usage of memory shouldn't bother you, because this memory will use in the future as cached page if you'll read it.

as @NightOwl888 said, if you're only writing you can use the SimpleFSDirectory

**Comment by rclabo** [comment]
>I'm facing the issue of high memory because of MMapDirectory. In my scenario, I'm opening 100 directories and writers respectively for 100 different indexes. After writing around 1 million documents, the process reaches around 35 GB. I took the dump of that process, after analysis of that dump. I found that there is a lot of memory consumption because of MMapDirectory.

I'm curious.  When you were seeing that memory consumption, had you written 1 million documents to all 100 indexes.  Ie. 100 million documents total?  Also just for out of curiosity, how many fields were in the typical index?

**Comment by hamzashoukat94** [comment]
I am feeling awesome that you are interested in my issue. I had noticed that memory consumption when I indexed 1 million documents in total. And there were a different number of fields 100s of fields in each document.

**Comment by rclabo** [comment]
That does seem really odd to me that such a situation would use 35 GB.  I have ran tests in the past, that while not quite the same, didn't need anything like that much memory. In one test I had 100 indexes open each with quite a few docs (cant remember how many) and in another test I had created one index with 500,000 docs.  But it ran fine on my machine that only has 16 GB and I had many other apps running as well.  

Is it possible for your to share your data and code?  If so that would be ideal.  If not can you provide more information about the type of each field used in the documents?  And info on the typical size of any text or byte arrays stored in those fields?  I'd be interested to try to replicate what you saw because that seems very unusual to me.

**Comment by NightOwl888** [comment]
@rclabo 

I suspect this has something to do with the fact that .NET Framework uses `WeakDictionary` rather than `ConditionalWeakTable` to manage weak references. When running experiments, I discovered that `WeakReference<T>` (used by `WeakDictionary`) hangs onto references when they go out of scope for some time, where `ConditionalWeakTable` releases references much more quickly.

I found [an implementation of `ConditionalWeakTable` for .NET 3.5](https://github.com/Dual-Iron/weak-tables/tree/master/src/Collections), but it also [holds onto references much longer than `ConditionalWeakTable`](https://github.com/Dual-Iron/weak-tables/issues/1#issuecomment-954272988). Unfortunately, without being able to tie directly into the garbage collector in native code the way `ConditionalWeakTable` does, there doesn't seem to be a realistic alternative to duplicating the behavior.

Of course, on .NET Core you will never hit this memory management problem because it is using `ConditionalWeakTable` throughout and doesn't even compile `WeakDictionary` into the release.

Although #256 is still open, we have nearly exhausted every possibility except going to Microsoft and requesting that they re-release `ConditionalWeakTable` with an enumerator on .NET Standard 2.0 and changing our .NET Framework target to at least `net461` (to utilize the .NET Standard 2.0 package) so we can eliminate the use of `WeakDictionary` entirely.

**Comment by rclabo** [comment]
@NightOwl888 Gotcha.  If he is running .NET Framework version rather then .NET Core this that makes total sense and no need to dig further.

@hamzashoukat94 Can you confirm you saw this memory consumption while using LuceneNET with .NET Framework rather then .NET Core, .Net5 or .NET6 ?

**Comment by hamzashoukat94** [comment]
Yes @rclabo I can confirm that I observed this memory consumption issue while using .NET Framework.

**Comment by hamzashoukat94** [comment]
Suggestion: 

I have read all the discussion. I came  to point that we should implement our own `ConditionalWeakTable` by extending it. The main difference I analyzed that the problem of enumerator in `ConditionalWeakTable` because in `.NETSTANDARD2.0`, there is no support of enumerator in this class. So, we can implement our own enumerator in our wrapper class. As, we are using this class for FieldCaching which is specific to LUCENENET. Then we should not need to wait for Microsoft to re-release `.NetStandard2.0` by providing enumerator in this class. We should not be dependent on Microsoft entirely.

**Comment by NightOwl888** [comment]
@hamzashoukat94 

Thanks for the suggestion. We have done a LOT of exploration on this issue already, and we are at a dead end with extending `ConditionalWeakTable` (see #256). It is designed to hold *weak* references on its keys, so there is no way to enumerate them without creating *strong* references (which defeats the whole purpose). And since in native C++ code, they tie directly into the garbage collector, there is effectively no way to add the APIs that are required to make an enumerator.

We actually have 2 missing APIs on .NET Fraemwork/.NET Standard 2.0:

- [GetEnumerator()](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.conditionalweaktable-2.system-collections-generic-ienumerable-system-collections-generic-keyvaluepair-tkey-tvalue---getenumerator?view=net-6.0)
- [AddOrUpdate](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.conditionalweaktable-2.addorupdate?view=net-6.0)

### GetEnumerator()

I took a look and we only have 4 classes that depend on the enumerator.

- [ByteBufferIndexInput](https://github.com/apache/lucenenet/blob/master/src/Lucene.Net/Store/ByteBufferIndexInput.cs#L409)
- [CachedOrdinalsReader](https://github.com/apache/lucenenet/blob/41ffbc7b54cd5427a87e63c8bc3c4c3c290e1161/src/Lucene.Net.Facet/Taxonomy/CachedOrdinalsReader.cs#L211)
- [CachingWrappingFilter](https://github.com/apache/lucenenet/blob/master/src/Lucene.Net/Search/CachingWrapperFilter.cs#L181)
- [IndexReader](https://github.com/apache/lucenenet/blob/master/src/Lucene.Net/Index/IndexReader.cs#L203)

Since we don't have a way to replicate a weak enumerator, it occurred to me that we may be able to use _weak events_ to call the instances without keeping references to them. It turns out that in WPF, this very problem was already solved with [weak event patterns](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/weak-event-patterns?view=netframeworkdesktop-4.8). I put together a [proof of concept](https://github.com/NightOwl888/WeakEventPoC) and it turns out you can attach weak events without holding references to the event targets. I wasn't able to work out a way to do it without the target knowing about its event source, but we can probably use internal fields that are set transparently (rather than in the constructor as in the example) to work around this limitation.

I believe this solves the problem for .NET Framework, but not for all of .NET Standard 2.0. However, [WeakEventManager](https://referencesource.microsoft.com/#windowsbase/Base/System/Windows/WeakEventManager.cs) doesn't appear to have any native dependencies (other than `ConditionalWeakTable`'s dependencies), so I believe we can port it and all of its dependences in their entirety to .NET Standard 2.0 to completely work around the lack of enumerator on .NET Standard 2.0 and .NET Framework.

Alternatively, we could use a 3rd party package, such as https://github.com/taori/Amusoft.EventManagement instead of porting the `WeakEventManager` from .NET Framework.

### AddOrUpdate

This is less of a problem than the enumerator, and there are effectively 3 ways to work around it:

1. Call `Add()` and if there is an `ArgumentException` (key already exists) call `Remove()` followed by `Add()`.
2. Call `TryGetValue()`. If the return value is `false`, call `Add()`, if it is true, call `Remove()` followed by `Add()`.
3. Always call `Remove()` followed by `Add()`.

I suspect checking either using the exception or `TryGetValue` will be more efficient than removing without first checking to see if the element is there, but it probably needs to be taken on a case-by-case basis to work out which method to use. Each case will also require some form of locking to ensure both the check and the operation(s) occur atomically.

**Comment by NightOwl888** [comment]
@hamzashoukat94

I just submitted #613 with the patch using weak events. This completely eliminates the `WeakDictionary` class and replaces the `ConditionalWeakTable` enumerator functionality with weak events.

When you get a chance, please download the packages from [the nuget artifact here](https://dev.azure.com/LuceneNET-Temp/Lucene.NET/_build/results?buildId=1941&view=artifacts&pathAsName=false&type=publishedArtifacts) and re-run the indexing and let us know if this fixes the high memory allocation.

**Comment by hamzashoukat94** [comment]
@NightOwl888  

I appreciate your interest in this issue. 

I'm here to tell you one thing we have another in a critical phase. I will test your changes as soon I am free from the current release. 

One thing I want to mention here is you people are very amazing and love to work with you. Hope so we will work in future also.

Thanks

**Comment by NightOwl888** [comment]
@hamzashoukat94 

[4.8.0-beta00016](https://www.nuget.org/packages/Lucene.Net/4.8.0-beta00016) includes #613, which should now resolve this issue. Feel free to reopen the issue if you find that it does not.
