### ISSUE TITLE
-Pre is not a known parameter

### ISSUE THREAD

**Issue by justcurious** [apache/lucenenet#610]
The landing page (https://lucenenet.apache.org/index.html) says

![image](https://user-images.githubusercontent.com/395328/150666072-410eb277-72d6-492a-93c8-aceb40d839c8.png)

`-Pre ` doesn't seem to be a known parameter for `Install-Package` 
https://docs.microsoft.com/en-us/nuget/reference/ps-reference/ps-ref-install-package
https://docs.microsoft.com/en-us/powershell/module/packagemanagement/install-package?view=powershell-7.2

If it's an alias then it should be replaced with the canonical parameter so users know what installing with that parameter does.

**Comment by justcurious** [comment]
I don't know what running that with `-Pre` will give me

**Comment by NightOwl888** [comment]
Hi there. Thanks for pointing that out. It was copied from NuGet.org verbatim several years ago, and being that we never use that command on multi-targeted libraries, we were unaware the syntax has changed.

It looks like the switch was changed at some point to `-AllowPrereleaseVersions` instead of the shortened form `-Pre`. Although, it boggles the mind why the old switch is no longer aliased.

https://docs.microsoft.com/en-us/powershell/module/packagemanagement/install-package?view=powershell-7.2

**Comment by rclabo** [comment]
The content for the website home page has been updated and this issue has been [resolved](https://github.com/apache/lucenenet/commit/b83d07c2ac6a82d82109651c15514409d061670f).  

Additionally the [lucenenet.apache.org](https://lucenenet.apache.org/) website now has a new [Quick Start](https://lucenenet.apache.org/quick-start/index.html) section that makes it easier for developers to get up to speed on using Lucene.NET.  This section include two step-by-step tutorials.
