### ISSUE TITLE
Is there any Lucene.NET object mapper? 

### ISSUE THREAD

**Issue by ahmadmdabit** [apache/lucenenet#630]
Hello,
**Is there an efficient Lucene.NET object mapper?** 
Best Regards,

**Comment by NightOwl888** [comment]
While this is something I wanted to do before the 4.8.0 release, it probably isn't going to make the cut unless it is contributed by the community.

Since Lucene.NET 4.8.0 is still a pre-release, most of the ORM tools out there are not compatible with the latest beta so would need to be recompiled at the least and possibly have some design changes to be compatible.

- [LukeMapper](http://intelligiblebabble.com/lukemapper-a-super-fast-orm-for-lucenenet/) - Hasn't been updated since Lucene.NET 2.9.4.1, but takes an interesting Dapper-like approach to generate efficient code. More info [here](http://intelligiblebabble.com/lukemapper-a-super-fast-orm-for-lucenenet/).
- [Lucene.Net.Linq](https://github.com/chriseldredge/Lucene.Net.Linq) - Hasn't been updated since Lucene.NET 3.0.3. More about it [here](https://chris.eldredge.io/blog/2012/05/08/Introducing-Linq-to-Lucene/).
- [Flucene](https://github.com/alex-titarenko/flucene) - Hasn't been updated since Lucene.NET 3.0.3.
- [Lucene.Net.DocumentMapper](https://www.nuget.org/packages/Lucene.Net.DocumentMapper) - compatible with 4.8.0-beta00016
- [Lucene.Net.ObjectMapping](https://www.nuget.org/packages/Lucene.Net.ObjectMapping) - Hasn't been updated since Lucene.NET 3.0.3.
- [Lucene2Objects](https://www.nuget.org/packages/Lucene2Objects) - Hasn't been updated since Lucene.NET 2.9.2. More info [here](http://davidcondemarin.blogspot.com/2012/03/introducing-lucene2objects.html).
- [LuceneNetExtensions](https://www.nuget.org/packages/LuceneNetExtensions) - Hasn't been updated since Lucene.NET 3.0.3.
- [ActiveLucene.Net](https://www.nuget.org/packages/ActiveLucene.Net) - Hasn't been updated since Lucene.NET 3.0.3.
- [LrNet.Lucene.Fluent](https://www.nuget.org/packages/LrNet.Lucene.Fluent) - Hasn't been updated since Lucene.NET 2.9.4.1.

This list may not be everything that exists, but this should get the ball rolling. Unfortunately, since I haven't experimented with any of these libraries, I cannot tell you how they perform or how easy they are to use.

> If anyone wants to experiment with these and come up with an approach that we can use to either integrate using partial classes in the Support folder or extend Lucene.NET with another NuGet package, please join the discussion. Ideally, whatever approach is taken would have both an attribute-based and a fluent API configuration, similar to Entity Framework.

**Comment by NightOwl888** [comment]
LukeMapper uses [Reflection.Emit](https://docs.microsoft.com/en-us/dotnet/framework/reflection-and-codedom/emitting-dynamic-methods-and-assemblies) to generate on-demand MSIL code at runtime, which it compiles and caches after the first hit. This is a very good approach that will have a small impact on runtime performance.

However, the object mapping could potentially be made into a compile-time [source generator](https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/source-generators-overview), which would eliminate the need for the initial runtime compile and cache. In other words, there would be absolutely no runtime performance impact because it would generate the cumbersome-to-maintain code based on the easy-to-maintain configuration, which would be compiled into the end user's assembly. There is an extensive [list of source generators](https://github.com/amis92/csharp-source-generators#readme) being maintained where various approaches to source generation can be analyzed.

LukeMapper's entry point is on `IndexSearcher`. `IndexSearcher` [may be used with `SearcherManager` to make it threadsafe](https://github.com/apache/lucenenet/issues/616#issuecomment-1054364945), which should be taken into account in the design.
