### ISSUE TITLE
Can support RedisDirectory

### ISSUE THREAD

**Issue by ricoisme** [apache/lucenenet#631]
hi 

I think redisdirectory is more useful than ramdirectory in real world.
I hope can support redisdirectory if we can.

Thanks

**Comment by NightOwl888** [comment]
There is no Redis support in [Lucene 4.8.0](https://github.com/apache/lucene/tree/releases/lucene-solr/4.8.0), so it won't be included in Lucene.NET.

However, since the Lucene `Directory` class is extensible, there are other Java projects that have Redis support that can be ported to .NET to support Redis.

- https://github.com/shijiebei2009/RedisDirectory
- https://github.com/DDTH/ddth-lucext#redisdirectory
- https://github.com/maxpert/RedisDirectory

**Comment by ricoisme** [comment]
I got it.
Thanks
