### ISSUE TITLE
[Help] Fail to compile official tutorial example

### ISSUE THREAD

**Issue by cigoic** [apache/lucenenet#641]
Hi,

I followed the tutor installing the latest 4.8.0 beta Lucent. However, the code cannot pass compiling as shown below. 
The Assembly references to the wrong version of Lucene (3.0.3). 

I have tried remove the NuGet packages and reinstall again. It did not help. Any suggestion? Thanks!

![截圖 2022-07-13 下午6 47 55](https://user-images.githubusercontent.com/2939228/178718745-5af84635-e75a-4ac0-80d5-b604a85e0f94.jpg)
![截圖 2022-07-13 下午7 02 05](https://user-images.githubusercontent.com/2939228/178718981-a520a75a-9522-4d11-8d46-69e0dc580ee5.jpg)

**Comment by rclabo** [comment]
Thank you for your question.  I wrote the tutorial and will try to help you.  The tutorial makes no reference to Lucene.NET 3.0.3 and is instead for Lucene.NET 4.8.

 

Perhaps when you added the NuGet reference you left out the –prerelease switch.  (see https://lucenenet.apache.org/quick-start/tutorial.html#add-nuget-references) 

 

The command should be:

 

dotnet add package Lucene.Net --prerelease

 

 

The –prerelease part of that command is what will add the reference to the Lucene.NET 4.8  since it’s still in beta.  If you leave out –prerelease then it will create a reference to 3.0.3 which is incorrect and will not compile.

 

You can confirm that it referenced the correct version of Lucene.NET by looking at  the .csproj file created (https://lucenenet.apache.org/quick-start/tutorial.html#viewing-the-two-main-files  )

 

In that project file, the following two lines should show the latest beta version of Lucene.Net 4.8

 

<PackageReference Include="Lucene.Net" Version="4.8.0-beta00016" />

<PackageReference Include="Lucene.Net.Analysis.Common" Version="4.8.0-beta00016" />

 

Please let me know if this clears up your issue.

 

Thank you for trying out Lucene.NET.  It’s a great open source Search Library.

 

Best,

 

-Ron 

rclabo

 

From: Jim Chiu ***@***.*** 
Sent: Wednesday, July 13, 2022 7:07 AM
To: apache/lucenenet
Cc: Subscribed
Subject: [apache/lucenenet] [Help] Fail to compile official tutorial example (Issue #641)

 

Hi,

I followed the tutor installing the latest 4.8.0 beta Lucent. However, the code cannot pass compiling as shown below.
The Assembly references to the wrong person of Lucene (3.0.3).

I have tried remove the NuGet packages and reinstall again. It did not help. Any suggestion? Thanks!

 <https://user-images.githubusercontent.com/2939228/178718745-5af84635-e75a-4ac0-80d5-b604a85e0f94.jpg> 截圖 2022-07-13 下午6 47 55
 <https://user-images.githubusercontent.com/2939228/178718981-a520a75a-9522-4d11-8d46-69e0dc580ee5.jpg> 截圖 2022-07-13 下午7 02 05

**Comment by rclabo** [comment]
In your screenshot I see that the GUI shows that you have a NuGet references to `Lucene.Net` Version 4.8.0-beta00016 and `Lucene.Net.Analysis.Common` Version 4.8.0-beta00016.  And yet the GUI is saying it can't resolve the referenced to `StandardAnalyzer` and doesn't recognize the `Lucene.Net.Analysis.Standard` namespace.  

That class and namespace is in the `Lucene.Net.Analysis.Common `Version 4.8.0-beta00016 NuGet package.  So it's odd the GUI isn't seeing them in that package.  You might try saving everything and then restarting the development environment.  Maybe it will then see the `StandardAnalyzer`  and  the `Lucene.Net.Analysis.Standard` namespace.

**Comment by cigoic** [comment]
Thanks a lot!

I end up restart VS2022, delete the solution folder and create a new project from beginning. This did help me start Lucene tutorial examples.

**Comment by cigoic** [comment]
> In your screenshot I see that the GUI shows that you have a NuGet references to `Lucene.Net` Version 4.8.0-beta00016 and `Lucene.Net.Analysis.Common` Version 4.8.0-beta00016. And yet the GUI is saying it can't resolve the referenced to `StandardAnalyzer` and doesn't recognize the `Lucene.Net.Analysis.Standard` namespace.
> 
> That class and namespace is in the `Lucene.Net.Analysis.Common `Version 4.8.0-beta00016 NuGet package. So it's odd the GUI isn't seeing them in that package. You might try saving everything and then restarting the development environment. Maybe it will then see the `StandardAnalyzer` and the `Lucene.Net.Analysis.Standard` namespace.

Yes. VS2022 17.3 preview did not update namespace references completely. I did install Lucene 3.0.3 at first by mistake. However, update it to 4.8 beta directly does not solve the problem. 

Create a total new solution folder seems to solve it. Thanks.
