### ISSUE TITLE
Add .Net 7 Tests

### ISSUE THREAD

**Issue by nikcio** [apache/lucenenet#717]
> (Before edit)
> As .Net 7 is just around the corner it would be great to look into what is needed to add explicit support to the new version.

Assignment is stated in the response from @NightOwl888 

- [x] Remove `netcoreapp3.1` (https://github.com/apache/lucenenet/pull/735)
- [ ] Add .Net 7 test support
- [ ] Update the [build instructions](https://github.com/apache/lucenenet/blob/dc2955699e2b8a2bf31813a819d17749eb7d4a4b/README.md#visual-studio) to indicate we no longer support building with VS2019

**Comment by NightOwl888** [comment]
Unless we are going to make the effort to migrate to new APIs, IMO it doesn't make much sense to add a new target. In fact, we are evaluating whether to drop one of the targets (either `net462` or `netstandard2.0`), since these have significant overlap and `netstandard2.1` pretty much covers all other platforms except .NET Framework and .NET 6+.

However, adding .NET 7 tests to Azure DevOps is a must. Adding .NET 7 tests to GitHub Actions should only be done if we remove the tests for .NET 6, since we only need one set of tests to validate the `net6.0` target and we want the PR tests to run as fast as possible.

Adding a target for `net6.0` made sense because:

1. J2N uses [hardware intrinsics](https://devblogs.microsoft.com/dotnet/hardware-intrinsics-in-net-core/) for some of the low level bit operations and `net6.0` supports both Windows and Linux
2. Normal dictionaries support deleting while iterating forward, so we don't have to use `ConcurrentDictionary<TKey, TValue>`

Being that we only have a couple of months left of `netcoreapp3.1` support, we should drop those tests but keep the `net5.0` tests for testing the `netstandard2.1` target. `net5.0` makes more sense to use because it supports detecting fatal crashes, where `netcoreapp3.1` does not. It would be best to first do a PR for dropping `netcoreapp3.1` tests, then a PR for adding the `net7.0` tests.

### Azure DevOps / build.bat

x64 + x86 on Windows only

- `net7.0` -> tests `net6.0` tfm
- `net6.0` -> tests `net6.0` tfm
- `net5.0` -> tests `netstandard2.1` tfm
- `net48` -> tests `net462` tfm
- `net461` -> tests `netstandard2.0` tfm (will probably drop both of these)

### GitHub Actions

x64 only on all targets

- `net7.0` -> tests `net6.0` tfm
- `net5.0` -> tests `netstandard2.1` tfm
- `net48` -> tests `net462` tfm
- `net461` -> tests `netstandard2.0` tfm (will probably drop both of these)

**Comment by NightOwl888** [comment]
FYI - I upgraded the [Git Tools plugin](https://github.com/yysun/git-tools/pull/41) that I use to review working changes so it is compatible with VS2022. So, that clears the path for adding .NET 7 tests since I am finally able to move beyond VS2019, which has been out of support since April, 2022.

The plugin saves so much time during reviews that it simply wasn't worth it to upgrade Visual Studio without it.

We will have to phase out support for VS2019 (and update the [build instructions](https://github.com/apache/lucenenet/blob/dc2955699e2b8a2bf31813a819d17749eb7d4a4b/README.md#visual-studio) accordingly) in order to add support for .NET 7.
