### ISSUE TITLE
Creating QueryParserTokenManager writes to standard output

### ISSUE THREAD

**Issue by xsharper** [apache/lucenenet#792]
Constructor of Lucene.Net.QueryParsers.Classic.QueryParserTokenManager  invokes InitBlock() private method, which initializes unused debug stream as 

`new StreamWriter(Console.OpenStandardOutput(), Console.Out.Encoding);`

This is unnecessary, and causes ill effects in applications using the console. For example:

```
Console.OutputEncoding=Encoding.UTF8;
var std= new StandardAnalyzer(LuceneVersion.LUCENE_48, StandardAnalyzer.STOP_WORDS_SET);
Console.Write("A");
var qp = new MultiFieldQueryParser(LuceneVersion.LUCENE_48, new[] {"test"}, std);
Console.Write("B");
```

outputs data between A and B:
```
A  B
```

**Comment by laimis** [comment]
It does sure looks like it's not being used anywhere. I looked at the Java version 4.8, and the code matches what we have ported. But then, in the latest version, it's all commented out. They most likely realized that they are not using it either. Example:

https://github.com/apache/lucene/blob/main/lucene/queryparser/src/java/org/apache/lucene/queryparser/classic/QueryParserTokenManager.java#L24

It feels like it's a simple enough code change...

**Comment by eladmarg** [comment]
if so, we can comment this as well.

**Comment by laimis** [comment]
@xsharper I just gave this a spin and can't reproduce it. Here is my code: https://github.com/laimis/lucene-issue-792

Perhaps you are using a different library version, not the latest beta build? Check out my csproj for references that I am using.

**Comment by laimis** [comment]
Closing this issue as I haven't heard back from the poster. I was not able to reproduce the issue with the latest beta builds: https://github.com/laimis/lucene-issue-792/blob/main/Program.cs

I am sure we will comment out the debug stream once we port to further versions, but I am reluctant to do so ahead of those efforts as we are adding changes to complete 4.8

**Comment by xsharper** [comment]
Sorry, didn't realize it's specific to stdout implementation in .NET 4.8 on Windows. With project file as below

luceneplayground.exe >output.txt

produces 5 bytes:

41 EF BB BF 42



` <Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Lucene.Net" Version="4.8.0-beta00016" />
    <PackageReference Include="Lucene.Net.Analysis.Common" Version="4.8.0-beta00016" />
    <PackageReference Include="Lucene.Net.QueryParser" Version="4.8.0-beta00016" />
  </ItemGroup>
</Project>`

**Comment by laimis** [comment]
I was able to dig into this further, and this is rather bizarre. So first, I confirmed that Lucene.NET codebase is not doing anything funky here and is not writing those bytes explicitly. It's .net framework writing a BOM marker out when it does this in QueryParserTokenManager:

`temp_writer = new StreamWriter(Console.OpenStandardOutput(), Console.Out.Encoding);
temp_writer.AutoFlush = true;`

In your code example, you set the Console.OutputEncoding to Encoding.UTF8 and that's what it gets back when doing Console.Out.Encoding. AutoFlush being set to true flushes the stream behind the scenes and flushes the BOM marker.

Why doesn't it do that in .net 7 (that's the only .net core fx I tried, it might not be doing that in other .net core versions either)? It appears that something is different between framework versions as to how this line is handled:

`Console.OutputEncoding=Encoding.UTF8;`

I wrote a quick test where I output to console Console.OutputEncoding and Console.Out.Encoding properties:

`
Console.WriteLine("before Console.Out encoding: " + Console.Out.Encoding);
Console.WriteLine("before Console.OutputEncoding: " + Console.OutputEncoding);
Console.OutputEncoding=System.Text.Encoding.UTF8;
Console.WriteLine("after Console.Out encoding: " + Console.Out.Encoding);
Console.WriteLine("after Console.OutputEncoding: " + Console.OutputEncoding);
`

In .net fx 4.8, here is the output on my machine:

> before Console.Out encoding: System.Text.SBCSCodePageEncoding
> before Console.OutputEncoding: System.Text.SBCSCodePageEncoding
> after Console.Out encoding: System.Text.UTF8Encoding
> after Console.OutputEncoding: System.Text.UTF8Encoding

Now .net 7:

> before Console.Out encoding: System.Text.OSEncoding
> before Console.OutputEncoding: System.Text.OSEncoding
> after Console.Out encoding: System.Text.ConsoleEncoding
> after Console.OutputEncoding: System.Text.UTF8Encoding

System.Out.Encoding in .net 7 is not set to UTF8Encoding when you set Console.OutputEncoding and thus the BOM marker is not written out.

Really bizarre.

Anyway, I will keep this issue open because we can comment out the code that Lucene Java version commented out but at least we know exactly what's going on. You could argue that perhaps Console.Out.Encoding should not be used in QueryParserTokenManager and instead Console.OutputEncoding should be used. But that's the only place where this is happening and commenting out should close the chapter on this.

**Comment by xsharper** [comment]
The issue different though. Encoding is just use used to demonstrate it. 

The problem is that in .NET 4.8 doing some backend processing, that isn't expected to output _anything_ to the console or network, by merely 

`var qp = new MultiFieldQueryParser(LuceneVersion.LUCENE_48, new[] {"test"}, std);`

does write to console as a side effect.

**Comment by NightOwl888** [comment]
Gotcha. Yeah, I see that is in our codebase, now.

There are a couple of things wrong here. 

1. This doesn't match the Java source, which only writes to `System.out`. 
2. We have created a seam for console writing at `Lucene.Net.Util.SystemConsole` that is not being utilized, but it should be.

So, you (will) have the ability to redirect the output that is being written in 2 ways:

1. Replace `Lucene.Net.Util.SystemConsole.Out` with a no-op `TextWriter`.
2. Call `QueryParserTokenManager.SetDebugStream(TextWriter)` with either a no-op `TextWriter` or a `TextWriter` that has already been disposed.

In 4.8.0-beta00016 and prior, the only option you have to disable this is option 2.

**Comment by NightOwl888** [comment]
Actually, I am a bit puzzled why this is even here. There is nothing else in the file that writes to this field. 

But if it were set up like the original Lucene code, initializing the variable to a static instance is very cheap and it wouldn't write anything when calling the `Console.Out` getter to set the field. So, there is little downside in reverting back to the original implementation.
