### ISSUE TITLE
Semantic Search support

### ISSUE THREAD

**Issue by sbiaudet** [apache/lucenenet#865]
I propose to upgrade Lucene.Net to support semantic searches in the same way as the current JAVA version.

Proposal:

- Add support for vector fields
- Vector similarity search (Euclidian, Dot, Cosine)

**Comment by Jeevananthan-23** [comment]
+1

**Comment by NightOwl888** [comment]
This is virtually impossible to do in Lucene 4.8.0 because it requires binary format changes to the index to support and there is no precedent in Java for layering this functionality on top of Lucene 4.8.0. Not to mention, we lose the ability to debug if we don't have a Lucene version to compare execution paths with and the test framework requires additional support to be built in to support newer versions. The only sensible way to do this is to upgrade the entire project to the entire version, not one feature at a time.

Given this functionality already exists in a later version, we will be implementing it when we do the upgrade. I am closing because this isn't an "issue" so much as something that is already part of the planned upgrade.
