### ISSUE TITLE
 If there is not enough funds, should lucenenet consider: opening up to receive funding from the community or industry ?

### ISSUE THREAD

**Issue by sgf** [apache/lucenenet#874]
The development of lucenenet seems to be very slow. If there is not enough funds, should lucenenet consider: opening up to receive funding from the community or industry. I believe there should be some support. 

If you are lucky, it will greatly improve the development of lucenenet. There are so many projects under the Apache Foundation, I guess the support that Apache can give should be very limited.

lucene.net is a crucial link in building the .net community ecology, but it lags far behind Java. Of course, this is not only because lucene.net lags behind lucene, but also because of the great success and influence of elastic search. So maybe lucene.net should do something.

**Comment by rclabo** [comment]
Thank you for sharing your concerns and for recognizing the importance of Lucene.NET in the .NET community. Your feedback provides valuable insight into the sentiments and aspirations of our user base.

It's accurate that Lucene.NET's development pace has been slower compared to its Java counterpart. Our team, comprised of dedicated volunteers, is doing its best with the resources we have.

Regarding funding and support: The Apache Software Foundation (ASF), which oversees Lucene.NET among many other projects, emphasizes neutrality and independence in all its projects. While the ASF accepts donations, these are channeled into benefiting the broader foundation rather than specific projects. This means individual projects, such as Lucene.NET, do not and cannot directly solicit or receive funds.

However, it's worth mentioning that many Apache committers, across various projects, do receive compensation, but not from the ASF directly. Some, for example, are sponsored by their employers to work on Apache projects, as these projects may align with the company's interests or products.

Despite many companies utilizing Lucene.NET in commercial products, there's been a noticeable lack of companies supporting their employees to contribute to Lucene.NET compared to the Java ecosystem. We're hopeful this will shift as the .NET landscape increasingly embraces open-source.

Lucene.NET holds an important role in the .NET ecosystem, and we are continuously exploring ways to ensure it remains competitive and relevant. We warmly welcome and encourage collaboration, insights, and any form of contribution that can further the project's growth.

Thank you again for your feedback, if you have any specific suggestions or insights on how to fund more resources for this project while keeping true to the Apache way, we are all ears.

**Comment by sgf** [comment]
thanks for your reply
