### ISSUE TITLE
Store the Lucene index in AWS S3 and allowing for efficient retrieval of records. 

### ISSUE THREAD

**Issue by harshalschaudhari** [apache/lucenenet#967]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

Save the Lucene index in AWS S3 for efficient record retrieval.

Proposed solution:

```C#
LuceneS3Directory s3IndexDir = S3Directory.Open(indexPath);
```

Additionally, the IndexWriter constructor should be modified to accept both LuceneS3Directory and indexConfig.

**Comment by Shazwazza** [comment]
This has been attempted before a few times with various implementations for things like Azure Blob Storage and SQL data stores. The problem is, Lucene requires super fast access to the its files. Lucene is entirely file based and sure, there's APIs to have a different Directory store, but ultimately if Lucene is not operating off of a fast disk, it will be very slow. The work around for this, is to sync the indexes so that Lucene operates off of a local files system (maybe in %temp%) and the Lucene Replicator is used to sync to a slow storage system so that when the process restarts, a sync from the slow system to the fast drive works.

I have implemented this for slow network drives to fast local drives https://github.com/Shazwazza/Examine/blob/support/3.x/src/Examine.Lucene/Directories/SyncedFileSystemDirectoryFactory.cs

I used to try to manage the implementation for Blog Storage but that was abandoned. However, this file system to file system syncing implementation has become pretty stable and could be used to swap out the slow network drive directory for something like AWS.

This won't be something that would be put into the Lucene.NET codebase though.
